version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-apache-node-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
            - public
            - build
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache py-pip bash ca-certificates openssl
            update-ca-certificates
            pip install awscli ecs-deploy
            wget https://s3-us-west-2.amazonaws.com/pn-circleci/customDeploy.sh && chmod +x customDeploy.sh
      - run:
          name: Build and push Image
          command: |
            bash customDeploy.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

